version: 2
updates:
  - # Maintain dependencies for GitHub Actions
    package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - # Maintain dependencies for Devcontainers
    package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
  - # Maintain dependencies for Dockerfiles
    package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily
