---
services:
  workspace:
    image: ubuntu:24.04
    stdin_open: true
    tty: true
    working_dir: /home/devcontainer/workspace
    volumes:
      - .:/home/devcontainer/workspace
    ports:
      - 443:443
      - 6443:6443
      - 80:80
    networks:
      devcontainer: {}
networks:
  devcontainer: {}
