---
services:
  tooling:
    image: ghcr.io/anselmes/devos:main
    entrypoint: /bin/bash
    # privileged: true
    stdin_open: true
    tty: true
    # user: root # note: required for /sbin/init
    working_dir: /home/devos/workspace
    # env_file:
    #   - .env
    volumes:
      - .:/home/devos/workspace
      - ~/.gitconfig:/home/devos/.gitconfig:ro
      - ~/.gnupg:/home/devos/.gnupg:ro
      - ~/.ssh:/home/devos/.ssh:ro
      - ~/.zshrc:/home/devos/.zshrc:ro
    ports: []
    # - 10022:22
    # - 10080:80
    # - 10443:443
    # - 15900:5900
    # - 16443:6443
