#!/usr/bin/env bash

set -eo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

CLOUDFLARE_MODE="false"
SOURCE_FILE="$DEFAULT_SOURCE_FILE"
OUTPUT_DIR="$DEFAULT_OUTPUT_DIR"
OUTPUT_TYPE="fqdn"

# MARK: - Help

usage() {
  cat << EOF
Usage: $0 [OPTIONS]

Extract host information from Terraform cluster output for Ansible

OPTIONS:
  --ip                    Extract IP addresses instead of FQDNs
  --fqdn                  Extract FQDNs     (default)
  --cloudflare            Use Cloudflare domain names instead of AWS FQDNs
  --src     FILE          Source YAML file  (default: $DEFAULT_SOURCE_FILE)
  --output  [DIR]         Output to files   (default: $DEFAULT_OUTPUT_DIR)
  --help                  Show this help message

ENVIRONMENT VARIABLES:
  CLUSTER_NAME    Cluster name prefix (default: kubernetes)
  DOMAIN          DNS domain (default: labsonline.ca)

EXAMPLES:
  $0                                              # Extract FQDNs to stdout
  $0 --output                                     # Extract FQDNs to $DEFAULT_OUTPUT_DIR
  $0 --output ./custom_dir                        # Extract FQDNs to custom directory
  $0 --ip --src ./custom.yaml                     # Extract IPs from custom file
  $0 --cloudflare                                 # Use Cloudflare domain names (role.domain)
  $0 --cloudflare --output                        # Generate Ansible vars with CF domains
  CLUSTER_NAME=production $0 --output ./prod_vars
EOF
}

# MARK: - Arguments

while [[ $# -gt 0 ]]; do
  case $1 in
    --ip)
      OUTPUT_TYPE="ip"
      shift
      ;;
    --fqdn)
      OUTPUT_TYPE="fqdn"
      shift
      ;;
    --cloudflare)
      CLOUDFLARE_MODE="true"
      shift
      ;;
    --src)
      SOURCE_FILE=$(parse_source_arg "$2")
      shift $([[ $# -gt 1 && ! $2 =~ ^-- ]] && echo 2 || echo 1)
      ;;
    --output)
      OUTPUT_DIR=$(parse_output_arg "$2" "$DEFAULT_OUTPUT_DIR")
      shift $([[ $# -gt 1 && ! $2 =~ ^-- ]] && echo 2 || echo 1)
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      handle_unknown_option "$1" usage
      ;;
  esac
done

# MARK: - Validation

check_file "$SOURCE_FILE" "Source file"
validate_yaml_tools

if [[ $CLOUDFLARE_MODE == "true" ]]; then
  hostname_mode="Cloudflare domain names ($DOMAIN)"
else
  hostname_mode="AWS FQDNs"
fi

# MARK: - Functions

generate_group_vars() {
  local group_name=$1
  shift
  local roles=("$@")

  echo "---"
  if [[ $CLOUDFLARE_MODE == "true" ]]; then
    echo "# Generated by $0 using Cloudflare domain names for cluster: $CLUSTER_NAME"
    echo "host_fqdns:"
  else
    echo "# Generated by $0 using ${OUTPUT_TYPE}s for cluster: $CLUSTER_NAME"
    echo "host_${OUTPUT_TYPE}s:"
  fi

  for role in "${roles[@]}"; do
    if [[ "$role" != "null" && -n "$role" ]]; then
      local value=$(extract_host_info "$role" "$SOURCE_FILE" "$OUTPUT_TYPE" "$CLOUDFLARE_MODE")
      if [[ "$value" != "null" ]]; then
        echo "  $role: $value"
      fi
    fi
  done
}

# MARK: - Main

echo "Extracting ${OUTPUT_TYPE}s for cluster: $CLUSTER_NAME from: $SOURCE_FILE"
echo "Hostname mode: $hostname_mode"

# Get available hosts for each role type
CP_ROLES=($(get_available_hosts "cp" "$SOURCE_FILE"))
MD_ROLES=($(get_available_hosts "md" "$SOURCE_FILE"))
MSR_ROLES=($(get_available_hosts "msr" "$SOURCE_FILE"))

# Extract values for display
CP_VALUES=()
MD_VALUES=()
MSR_VALUES=()

for role in "${CP_ROLES[@]}"; do
  CP_VALUES+=($(extract_host_info "$role" "$SOURCE_FILE" "$OUTPUT_TYPE" "$CLOUDFLARE_MODE"))
done

for role in "${MD_ROLES[@]}"; do
  MD_VALUES+=($(extract_host_info "$role" "$SOURCE_FILE" "$OUTPUT_TYPE" "$CLOUDFLARE_MODE"))
done

for role in "${MSR_ROLES[@]}"; do
  MSR_VALUES+=($(extract_host_info "$role" "$SOURCE_FILE" "$OUTPUT_TYPE" "$CLOUDFLARE_MODE"))
done

echo ""
echo "Available hosts found in $SOURCE_FILE:"
echo "Managers (${CLUSTER_NAME}-cp-*): ${CP_VALUES[*]}"
echo "Nodes (${CLUSTER_NAME}-md-*): ${MD_VALUES[*]}"
echo "MSR Nodes (${CLUSTER_NAME}-msr-*): ${MSR_VALUES[*]}"

# MARK: - Summary

if [[ -n "$OUTPUT_DIR" ]]; then
  echo ""
  echo "Generating Ansible group variable files in: $OUTPUT_DIR"

  ensure_directory "$OUTPUT_DIR"

  if [[ ${#CP_ROLES[@]} -gt 0 ]]; then
    generate_group_vars "cp" "${CP_ROLES[@]}" > "$OUTPUT_DIR/managers.yml"
    echo "Generated: $OUTPUT_DIR/managers.yml (${#CP_ROLES[@]} hosts)"
  else
    echo "No manager hosts found, skipping managers.yml"
  fi

  if [[ ${#MD_ROLES[@]} -gt 0 ]]; then
    generate_group_vars "md" "${MD_ROLES[@]}" > "$OUTPUT_DIR/nodes.yml"
    echo "Generated: $OUTPUT_DIR/nodes.yml (${#MD_ROLES[@]} hosts)"
  else
    echo "No worker node hosts found, skipping nodes.yml"
  fi

  if [[ ${#MSR_ROLES[@]} -gt 0 ]]; then
    generate_group_vars "msr" "${MSR_ROLES[@]}" > "$OUTPUT_DIR/msrnodes.yml"
    echo "Generated: $OUTPUT_DIR/msrnodes.yml (${#MSR_ROLES[@]} hosts)"
  else
    echo "No MSR hosts found, skipping msrnodes.yml"
  fi

  echo ""
  if [[ $CLOUDFLARE_MODE == "true" ]]; then
    echo "Content type: Cloudflare domain names (host_fqdns)"
  else
    echo "Content type: host_${OUTPUT_TYPE}s"
  fi
  echo "Hostname mode: $hostname_mode"
else
  echo ""
  if [[ ${#CP_ROLES[@]} -gt 0 ]]; then
    echo "=== Managers ==="
    generate_group_vars "cp" "${CP_ROLES[@]}"
    echo ""
  fi

  if [[ ${#MD_ROLES[@]} -gt 0 ]]; then
    echo "=== Nodes ==="
    generate_group_vars "md" "${MD_ROLES[@]}"
    echo ""
  fi

  if [[ ${#MSR_ROLES[@]} -gt 0 ]]; then
    echo "=== MSR Nodes ==="
    generate_group_vars "msr" "${MSR_ROLES[@]}"
  fi
fi
