---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
  annotations:
    checkov.io/skip1: CKV2_K8S_6=Not caring about Network Policies for now
spec:
  restartPolicy: Always
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 65536
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: busybox
      image: busybox@sha256:768e5c6f5cb6db0794eec98dc7a967f40631746c32232b78a3105fb946f3ab83
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
            - NET_RAW
      args:
        - /bin/bash
        - -c
        - touch /tmp/healthy; sleep 3600
      resources:
        limits:
          memory: 128Mi
          cpu: 500m
        requests:
          memory: 64Mi
          cpu: 250m
      livenessProbe:
        initialDelaySeconds: 5
        periodSeconds: 5
        exec:
          command:
            - cat
            - /tmp/healthy
      readinessProbe:
        initialDelaySeconds: 5
        periodSeconds: 5
        exec:
          command:
            - cat
            - /tmp/healthy
