---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: kubernetes
spec:
  hosts:
    - role: controller+worker
      noTaints: true
      ssh:
        address: 127.0.0.1
        keyPath: ~/.ssh_rsa
        port: 22
        user: ubuntu
      installFlags:
        - --enable-cloud-provider
        - --kubelet-extra-args="--cloud-provider=external"
  k0s:
    config: {}
