---
metadata:
  name: skiff
site:
  domain: labos.local
  config:
    pki:
      ca:
        days: 3065
        subj: /CN=skiff-root-ca
  service:
    libvirt:
      enabled: true
  vm:
    - name: skiff
      osinfo: ${os_url}/${os_name}/${os_version}
      arch: ${arch}
      cpu: ${cpu}
      image: ${image}
      memory: ${memory}
      cloudinit:
        enabled: true
      networks:
        interfaces:
          oam:
            address:
              mac: ba:be:fa:ce:00:00
              ipv4:
                dhcp: true
              ipv6:
                dhcpv6: true
status:
  gpg_dir: ${site_dir}/.gnupg
  libvirt_cloudinit_dir: ${libvirt_dir}/boot
  libvirt_emulator: $(command -v ${qemu-system-${arch})
  libvirt_firmware_file: ${firmware_dir}/edk2-${arch}-code.fd
  libvirt_image_dir: ${libvirt_dir}/images
  pki_ca_bundle: ${site_dir}/ca.pfx
  pki_ca_cert_file: ${site_dir}/pki/ca.crt
  pki_ca_key_file: ${site_dir}/pki/ca.key
  pki_dir: ${site_dir}/pki
  site_dir: /tmp/skiff
  ssh_key_file: ${site_dir}/id_ed25519
