binary:
  - name: helm
    url: https://get.helm.sh/helm-v${version}-${os}-${arch}.tar.gz
    version: 3.16.2
    type: archive
    archs:
      - amd64
      - arm64
  - name: kubectl
    url: https://dl.k8s.io/release/v${version}/bin/${os}/${arch}/kubectl
    version: 1.31.1
    type: executable
    archs:
      - amd64
      - arm64
package:
  add: []
  # - name: ""
  #   keyring: ""
  #   repo: ""
  #   type: apt
  remove: []
  # - name: containerd
  #   type: apt
  group: []
  # - name: docker
  #   keyring: https://download.docker.com/${os}/ubuntu/gpg
  #   repo: https://download.docker.com/${os}/ubuntu
  #   type: apt
  #   add:
  #     - containerd.io
  #     - docker-buildx-plugin
  #     - docker-ce-cli
  #     - docker-ce
  #     - docker-compose-plugin
  #   remove:
  #     - containerd
  #     - docker-compose
  #     - docker-doc
  #     - docker.io
  #     - podman-docker
  #     - runc
plugin:
  - name: kubectl
    installer: krew
    list:
      - access-matrix
      - ca-cert
      - cert-manager
      - cilium
      - config-import
      - ctx
      - debug-shell
      - deprecations
      - df-pv
      - hns
      - images
      - minio
      - node-shell
      - ns
      - nsenter
      - oidc-login
      - open-svc
      - openebs
      - pod-shell
      - rabbitmq
      - rook-ceph
      - view-cert
      - view-secret
      - view-utilization
      - view-webhook
      - virt
