#!/usr/bin/env bash

set -eo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

SOURCE_FILE="$DEFAULT_SOURCE_FILE"
OUTPUT_FILE="$DEFAULT_INVENTORY_FILE"

# MARK: - Help

usage() {
  cat << EOF
Usage: $0 [OPTIONS]

Generate Ansible inventory from Terraform cluster output

OPTIONS:
  --src     [FILE]        Source YAML file (default: $DEFAULT_SOURCE_FILE)
  --output  [FILE]        Output file (default: $DEFAULT_INVENTORY_FILE)
  --help                  Show this help message

ENVIRONMENT VARIABLES:
  CLUSTER_NAME        Cluster name prefix (default: kubernetes)

EXAMPLES:
  $0                                         # Generate inventory to $DEFAULT_INVENTORY_FILE from $DEFAULT_SOURCE_FILE
  $0 --src ./custom.yaml                     # Use custom host file
  $0 --output ./custom-inventory.yml         # Generate to custom output file
  $0 --src ./hosts.yaml --output ./inv.yml   # Custom source and output
  CLUSTER_NAME=prod $0 --output ./prod-inventory.yml
EOF
}

# MARK: - Arguments

while [[ $# -gt 0 ]]; do
  case $1 in
    --src)
      SOURCE_FILE=$(parse_source_arg "$2")
      shift $([[ $# -gt 1 && ! $2 =~ ^-- ]] && echo 2 || echo 1)
      ;;
    --output)
      OUTPUT_FILE=$(parse_output_arg "$2" "$DEFAULT_INVENTORY_FILE")
      shift $([[ $# -gt 1 && ! $2 =~ ^-- ]] && echo 2 || echo 1)
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      handle_unknown_option "$1" usage
      ;;
  esac
done

# MARK: - Validation

check_file "$SOURCE_FILE" "Source file"
validate_yaml_tools

# MARK: - Functions

extract_existing_hosts() {
  local node_type=$1
  local hosts=()

  for i in {0..2}; do
    local role_name="${CLUSTER_NAME}-${node_type}-${i}"
    local host_exists=$(yq eval "
      .spec.kubernetes.infra.hosts[] |
      select(.role == \"$role_name\") |
      .role
    " "$SOURCE_FILE" 2>/dev/null || echo "")

    if [[ -n "$host_exists" ]]; then
      hosts+=("$role_name")
    fi
  done

  echo "${hosts[@]}"
}

generate_inventory_section() {
  local group_name=$1
  local group_key=$2
  shift 2
  local hosts=("$@")

  if [[ ${#hosts[@]} -eq 0 ]]; then
    return
  fi

  # Detect which host variable is available for this group
  local host_var=$(detect_host_variable "$group_key")

  echo "    $group_key:"
  echo "      hosts:"
  for host in "${hosts[@]}"; do
    echo "        $host:"
    if [[ "$host_var" == "host_fqdns" ]]; then
      echo "          ansible_host: \"{{ host_fqdns['$host'] }}\""
    elif [[ "$host_var" == "host_ips" ]]; then
      echo "          ansible_host: \"{{ host_ips['$host'] }}\""
    else
      # Fallback: extract IP directly from source if no group_vars available
      local host_ip=$(extract_host_info "$host" "$SOURCE_FILE" "ip" "false")
      echo "          ansible_host: \"$host_ip\""
    fi
  done
  echo ""
}

# MARK: - Main

echo """
Generating Ansible inventory for cluster: $CLUSTER_NAME
Source: $SOURCE_FILE
Output: $OUTPUT_FILE
"""

CP_HOSTS=($(extract_existing_hosts "cp"))
MD_HOSTS=($(extract_existing_hosts "md"))
MSR_HOSTS=($(extract_existing_hosts "msr"))

# Ensure output directory exists
ensure_directory "$(get_output_dir "$OUTPUT_FILE")"

# Generate the inventory file
cat > "$OUTPUT_FILE" << EOF
---
# Generated by $0 for cluster: $CLUSTER_NAME
# Source: $SOURCE_FILE
all:
  children:
    mke_hosts:
      children:
        managers:
        nodes:
        msrnodes:

EOF

# Generate each section
generate_inventory_section "managers" "managers" "${CP_HOSTS[@]}" >> "$OUTPUT_FILE"
generate_inventory_section "nodes" "nodes" "${MD_HOSTS[@]}" >> "$OUTPUT_FILE"
generate_inventory_section "msrnodes" "msrnodes" "${MSR_HOSTS[@]}" >> "$OUTPUT_FILE"

# MARK: - Summary

# Show detected host variables
echo ""
echo "Detected host variables:"
if [[ ${#CP_HOSTS[@]} -gt 0 ]]; then
  echo "  managers: $(detect_host_variable "managers")"
fi
if [[ ${#MD_HOSTS[@]} -gt 0 ]]; then
  echo "  nodes: $(detect_host_variable "nodes")"
fi
if [[ ${#MSR_HOSTS[@]} -gt 0 ]]; then
  echo "  MSR: $(detect_host_variable "msrnodes")"
fi

echo """
Ansible inventory generated successfully!
  Source: $SOURCE_FILE
  Output: $OUTPUT_FILE
  Cluster: $CLUSTER_NAME

Host counts:
  Managers: ${#CP_HOSTS[@]} (${CP_HOSTS[*]})
  Nodes: ${#MD_HOSTS[@]} (${MD_HOSTS[*]})
  MSR Nodes: ${#MSR_HOSTS[@]} (${MSR_HOSTS[*]})

To use this inventory:
  ansible-playbook -i $OUTPUT_FILE your-playbook.yml
"""
