#!/usr/bin/env bash

set -eo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

TERRAFORM_DIR="$DEFAULT_TERRAFORM_DIR"
OUTPUT_DIR="$DEFAULT_OUTPUT_DIR"
OUTPUT_TYPE="fqdn"

# MARK: - Help

usage() {
  cat << EOF
Usage: $0 [OPTIONS]

Extract load balancer information from Terraform output for Ansible

OPTIONS:
  --ip                    Extract IP addresses instead of FQDNs
  --fqdn                  Extract FQDNs       (default)
  --terraform DIR         Terraform directory (default: $DEFAULT_TERRAFORM_DIR)
  --output    [DIR]       Output to files     (default: $DEFAULT_OUTPUT_DIR)
  --help                  Show this help message

EXAMPLES:
  $0                                    # Extract FQDNs to stdout
  $0 --output                           # Extract FQDNs to $DEFAULT_OUTPUT_DIR
  $0 --output ./custom_dir              # Extract FQDNs to custom directory
  $0 --ip --terraform ./terraform       # Extract IPs from custom terraform dir
  $0 --fqdn --output --terraform ./tf
EOF
}

# MARK: - Arguments

while [[ $# -gt 0 ]]; do
  case $1 in
    --ip)
      OUTPUT_TYPE="ip"
      shift
      ;;
    --fqdn)
      OUTPUT_TYPE="fqdn"
      shift
      ;;
    --terraform)
      TERRAFORM_DIR="$2"
      shift 2
      ;;
    --output)
      OUTPUT_DIR=$(parse_output_arg "$2" "$DEFAULT_OUTPUT_DIR")
      shift $([[ $# -gt 1 && ! $2 =~ ^-- ]] && echo 2 || echo 1)
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      handle_unknown_option "$1" usage
      ;;
  esac
done

# MARK: - Validation

check_directory "$TERRAFORM_DIR" "Terraform directory"

# MARK: - Functions

extract_dns_name() {
  local yaml_output="$1"

  # Extract dns_name from YAML output using yq or grep
  if command -v yq >/dev/null 2>&1; then
    echo "$yaml_output" | yq eval '.spec.dns_name // ""' -
  else
    # Fallback: use grep and sed to extract dns_name
    echo "$yaml_output" | grep -E '^\s*"dns_name":' | sed -E 's/.*"dns_name":\s*"([^"]+)".*/\1/'
  fi
}

resolve_value() {
  local dns_name="$1"

  if [[ -z "$dns_name" ]]; then
    echo ""
    return
  fi

  if [[ "$OUTPUT_TYPE" == "fqdn" ]]; then
    echo "$dns_name"
  else
    # Resolve to IP
    echo "$(resolve_to_ip "$dns_name")"
  fi
}

generate_lb_vars() {
  echo "---"
  echo "# Generated by $0 using ${OUTPUT_TYPE}s"
  echo "mke_lb_${OUTPUT_TYPE}: \"$MKE_LB_VALUE\""
  echo "msr_lb_${OUTPUT_TYPE}: \"$MSR_LB_VALUE\""
}

# MARK: - Main

echo "Extracting load balancer ${OUTPUT_TYPE}s from: $TERRAFORM_DIR"

MKE_LB_YAML=$(get_terraform_output "$TERRAFORM_DIR" "mke_lb_info")
MSR_LB_YAML=$(get_terraform_output "$TERRAFORM_DIR" "msr_lb_info")

MKE_LB_DNS=$(extract_dns_name "$MKE_LB_YAML")
MSR_LB_DNS=$(extract_dns_name "$MSR_LB_YAML")

MKE_LB_VALUE=$(resolve_value "$MKE_LB_DNS")
MSR_LB_VALUE=$(resolve_value "$MSR_LB_DNS")

echo """
Extracted load balancer ${OUTPUT_TYPE}s:
echo MKE Load Balancer: $MKE_LB_VALUE
echo MSR Load Balancer: $MSR_LB_VALUE
"""

# MARK: - Summary

if [[ -n "$OUTPUT_DIR" ]]; then
  echo ""
  echo "Generating Ansible load balancer variables in: $OUTPUT_DIR"

  ensure_directory "$OUTPUT_DIR"
  generate_lb_vars > "$OUTPUT_DIR/lb.yml"

  echo "Generated file:"
  echo "  - $OUTPUT_DIR/lb.yml"
  echo ""
  echo "Content type: mke_lb_${OUTPUT_TYPE}, msr_lb_${OUTPUT_TYPE}"
else
  echo ""
  echo "=== Load Balancer Variables ==="
  generate_lb_vars
fi
